
language: node_js

node_js:
 - stable

branches:
  only:
  - master

before_install:
  - npm config set registry=https://registry.npm.taobao.org/
  
install:
  - npm install

script:
 - npm run build